INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('001', 'Emergency circuit opened', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('002', 'Programma non selezionato', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('003', 'Circuito sicurezza operatore macchina aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('004', 'Circuito Sicurezza transporti contenitori aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('005', 'Circuito Sicurezza operatore magazzino pallete aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('017', 'Blocco manuale uscita contenitori', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('018', 'Blocco manuale entrata paletta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('019', 'Macchina in manuale', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('020', 'Macchina ferma senza allarmi', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('021', 'Arresto in fase macchina da operatore', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('022', 'Svuotamento macchina da operatore', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('026', 'Pallete non pronte in entrata', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('033', 'Emergenza premuta BOX-H', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('034', 'Emergenza premuta BOX-I', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('035', 'Emergenza premuta BOX-L', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('039', 'Emergenza premuta BOX-O', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('040', 'Emergenza premuta BOX-P', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('041', 'Emergenza premute BOX-Q', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('042', 'Emergenza premute BOX-R', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('043', 'Emergenza Premute BOX-S', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('044', 'Emergenza Premuta BOX-T', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('065', 'Porta aperta zona 1 Macchina', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('066', 'Porta aperta Zona 2 Transporti contenitori', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('067', 'Porta aperta zona 3 transporti uscita palette magazzino pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('073', 'Scatto Barriera zona 1 Macchina', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('075', 'Scato Barriera zona 3 transporti uscita pallete magazzino pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('185', 'Sezionatore motore 20Q5 aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('186', 'Sezionatore motore 21Q5 aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('187', 'Sezionatore motore 28Q5', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('188', 'Sezionatore motore 29Q5', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('189', 'Sezionatore motore 30Q5 aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('190', 'Sezionatore motore 31Q3 aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('191', 'Sezionatore motore 33Q3 aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('192', 'Sezionatore motore 34Q3 aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('193', 'Sezionatore motore 35Q3 aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('194', 'Sezionatore motore 44Q3 aperto', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('241', 'Scatto magnetotermico ausiliari', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('250', 'Overvoltage arrestor', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('261', 'Paracadute sollevamento strati bloccati', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('263', 'Paracadute sollevamento magazzino falde  bloccati', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('265', 'Paracadute sollevamento magazzino pallete  bloccati', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('273', 'Encoder spintore bloccato', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('274', 'Encoder sollevamento strati bloccato', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('275', 'Encoder toglifalde bloccato', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('276', 'Encoder magazzino flade bloccato', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('278', 'Encoder magazzino pallete bloccato', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('241', 'Scatto magnetotermico ausiliari', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('242', 'Scatto magnetotermico motori zona 1 (all motor)', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('388', 'Nodo profibus n° 20', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('305', 'Inverter 20U2 1°trasporto contenitori', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('389', 'Nodo Profibus n° 21', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('306', 'Inverter 21U2 2°trasporto contenitori', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('398', 'Nodo Profibus n° 30', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('327', 'Inverter 22U2 spintore', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('400', 'Nodo Profibus n° 32', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('328', 'Inverter 23U2 toglifalde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('401', 'Nodo Profibus n° 33', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('329', 'Inverter 24U2 sollevamento strati', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('403', 'Nodo Profibus n° 35', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('333', 'Inverter 36U2 magazzino falde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('408', 'Nodo Profibus n° 40', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('353', 'Inverter 26U2 trasporto centrale pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('409', 'Nodo Profibus n° 41', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('354', 'Inverter 27U2 I° trasporto ingresso pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('410', 'Nodo Profibus n° 42', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('355', 'Inverter 28U2 2° trasporto ingresso pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('411', 'Nodo Profibus n° 43', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('356', 'Inverter 29U2 3° trasporto ingresso pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('412', 'Nodo Profibus n° 44', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('357', 'Inverter 30U2 4° trasporto ingresso pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('373', 'Nodo Profibus n° 05', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('374', 'Nodo Profibus n° 06', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('376', 'Nodo Profibus n° 08', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('377', 'Nodo Profibus n° 09', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('378', 'Nodo Profibus n° 10', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('379', 'Nodo Profibus n° 11', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('380', 'Nodo Profibus n° 12', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('388', 'Nodo Profibus n° 20', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('389', 'Nodo Profibus n° 21', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('398', 'Nodo Profibus n° 30', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('400', 'Nodo Profibus n° 32', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('401', 'Nodo Profibus n° 33', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('403', 'Nodo Profibus n° 35', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('408', 'Nodo Profibus n° 40', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('409', 'Nodo Profibus n° 41', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('410', 'Nodo Profibus n° 42', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('411', 'Nodo Profibus n° 43', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('412', 'Nodo Profibus n° 44', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('423', 'Nodo Profibus n° 55', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('428', 'Nodo Profibus n° 60', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('433', 'Nodo Profibus n° 65', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('435', 'Nodo Profibus n° 75', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('436', 'Nodo Profibus n° 80', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('436', 'Nodo Profibus n° 85', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('451', 'Controllo FBK motore Spintore', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('452', 'Controllo FBK motore Toglifalde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('453', 'Controllo FBK motore Sollevamento strati', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('468', 'Controllo FBK motore Trasporto 26m5 centrale palleta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('469', 'Controllo FBK motore Trasporto I° trasporto ingresso palleta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('470', 'Controllo FBK motore Trasporto 2° trasporto ingresso palleta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('471', 'Controllo FBK motore Trasporto 3° trasporto ingresso palleta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('472', 'Controllo FBK motore Trasporto 4° trasporto ingresso palleta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('473', 'Controllo FBK motore Trasporto 5° trasporto ingresso palleta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('474', 'Controllo FBK motore Trasporto 6° trasporto ingresso palleta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('475', 'Controllo FBK motore Trasporto 7° trasporto ingresso palleta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('457', 'Controllo FBK motore magazzino falde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('458', 'Controllo FBK motore Forche magazzino falde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('467', 'Controllo FBK motore Trasporto 1° scario pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('466', 'Controllo FBK motore Trasporto 2° scario pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('455', 'Controllo FBK motore magazzino pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('456', 'Controllo FBK motore Forche magazzino pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('465', 'Controllo FBK motore Trasporto 3° scario pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('464', 'Controllo FBK motore Trasporto 4° scario pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('484', 'Controllo FBK inverter 20U2 I° trasporto contenitori', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('485', 'Controllo FBK inverter 21U2 2° trasporto contenitori', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('495', 'Controllo FBK inverter 22U2 spintore', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('496', 'Controllo FBK inverter 23U2 toglifalde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('497', 'Controllo FBK Inverter 24U2 sollevamento strati', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('501', 'Controllo FBK Inverter 36U2 Magazzino falde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('521', 'Controllo FBK 26U2 trasporto centrale pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('522', 'Controllo FBK inverter 27U2 I° trasporto ingresso pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('523', 'Controllo FBK inverter 28U2 2° trasporto ingresso pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('524', 'Controllo FBK inverter 29U2 3° trasporto ingresso pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('525', 'Controllo FBK inverter 30U2 4° trasporto ingresso pallete', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('556', 'Elettrovalvo la generale sicurezza bloccata', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('557', 'Elettrovalvo la generale sicurezza magazzino bloccata', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('561', 'Arresto uscita palleta bloccato', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('562', 'Portentrata palleta in  blocco', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('563', 'Guide laterali palleta in blocco', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('564', 'Spintore strato bloccato (torque)', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('565', 'Sagoma paletta trasporto centrale', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('566', 'Guide pneumatiche spintore in blocco', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('569', 'Sicurezza discesa sollevamento strati', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('570', 'Sicurezza salita sollevamento strati', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('571', 'Errore uscita paletta', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('572', 'paletta vuota bloccata su sollevamento', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('573', 'Pad remover device blocked', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('574', 'Cilindro salita/discesa toglifalde in blocco', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('575', 'Vacuostato presenza falda bloccato toglifalde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('576', 'Palleta con reggia(rimuoveremanulmente la reggia)', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('579', 'Sicurezza sollevamento maggazino falde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('580', 'Sicurezza forche magazzino falde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('583', 'Sicurezza sollevamento maggazino falde', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('584', 'Sicurezza forche magazzino palette', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('585', 'Magazino falde in blocco', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('587', 'Magazzino pallete in bloco', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('609', 'Errore Circuito Emergenza', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('610', 'Errore Circuito Porte Zona 1', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('611', 'Errore Circuito Porte Zona 2', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('612', 'Errore Circuito Porte Zona 3', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('618', 'Errore Circuito Barriere Zona 1', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('620', 'Errore Circuito Barriere Zona 3', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('631', 'Controllo FBK Contattori 245KM2-3', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('632', 'Controllo FBK Contattori 245KM4-5', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('633', 'Controllo FBK Contattori 251KM2-3', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('636', 'Controllo FBK Contattori 255KM2-3', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('641', 'Pressione aria bassa', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('786', 'Magazzino palette fuori posizione', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('787', 'Zona 3 Magazzino palette non in marcia', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('788', 'Toglifalde mancanza falda', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('790', 'Blocco cappucisullo scivolo', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('795', 'Comunicazione con depal IBG0215', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('796', 'Comunicazione contrasporti contenitori', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('809', 'Comunicazione PLC-Pannelo operatore BOX-H', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('810', 'Comunicazione PLC-Pannelo operatore BOX-I', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('819', 'Trasporto Sali-scendi ingresso bloccato', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('833', 'Temperatura armadio elettrico', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('834', 'Manzanza alimentazione generale armadio elettrico', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('841', 'UPS Battery operation', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('842', 'UPS Power supply 24VDC', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('843', 'UPS ALARM', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('844', 'UPS Operation OK', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('845', 'UPS Battery charger', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('857', 'Mancanza palette ingresso macchina', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('858', 'Uscita contenitori piena', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('859', 'Uscita paletta - Magazino palette pieno', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('860', 'Magazzino falde pieno', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('861', 'Magazzino cornici pieno', NOW(), NOW());
INSERT INTO alarms (code_alarm, description, created_at, updated_at) VALUES ('862', 'Magazzino cappuci pieno', NOW(), NOW());

INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergenct stop button', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Select Program', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), '1. Check the all access doors are closed,', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Program', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Program', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Select the automatic selector', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Push the button start', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergency stop button on the operator panel', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergency stop button on the operator panel', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergency stop button on the operator panel', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergency stop button on the operator panel', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergency stop button on the operator panel', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergency stop button on the operator panel', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergency stop button on the operator panel', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergency stop button on the operator panel', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check and reset the emergency stop button on the operator panel', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I23.0 Check 20Q5', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check feedback I23.1', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check feedback I71.4', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check feedback I71.5', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check feedback I71.6.', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I71.7', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I72.0', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I72.1', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I72.2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I61.2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I117.2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I117.3', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I20.2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I50.6', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I60.6', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check nilai encoder / Lakukan Homing', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check nilai encoder / Lakukan Homing', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check nilai encoder / Lakukan Homing', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check nilai encoder / Lakukan Homing', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check nilai encoder / Lakukan Homing', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I117.2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I117.1', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check nodo', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Inverter, Check Connection Profibus to Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Alarm Inverter', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check feedback I118.2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.3', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I21.4', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I20.4', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I20.6', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check nilai encoder / Lakukan Homing', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I21.6', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check 300S4', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I20.1 Check 310S4', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I20.0 Check 310S2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check 313B6', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I30.4', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I30.1', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check nilai encoder / Lakukan Homing', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I50.3', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check nilai encoder / Lakukan Homing', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check I60.3', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check 352B1 Check I61.0', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check all Emergency Button and Switch or Reset Profisafe', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check all Emergency Button and Switch or Reset Profisafe', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check all Emergency Button and Switch or Reset Profisafe', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check all Emergency Button and Switch or Reset Profisafe', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check all Emergency Button and Switch or Reset Profisafe', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check all Emergency Button and Switch or Reset Profisafe', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback Contactor 245KM2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback Contactor 245KM4', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback Contactor 251KM2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback Contactor 255KM2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check 350S6 Check I60.2, 350S4 Check I60.1', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'I30.0 320S1, I30.1 320S4,', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check 315B4 Check I22.5', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Ethernet Cable', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Ethernet Cable', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Ethernet Cable', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Ethernet Cable', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check 361B6 I70.6', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'I117.0 90M3', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Feedback I118.0, Check 12K2', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Battery', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Power Supply', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Battery', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Battery', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check Battery', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'Check 313B6 i21.6, 313B4 I21.5, 360B1 I70.0', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'I22.0 314B1', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'I60.0 350B1, I61.1 350B4', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'I50.0 340B1', NOW(), NOW());
INSERT INTO actions (alarm_id, action_text, created_at, updated_at) VALUES (LAST_INSERT_ID(), 'I22.4 315B1', NOW(), NOW());